### ISSUE TITLE
[Bug]: plus sign disappears after saving

### ISSUE THREAD

**Issue by conrad-heimbold** [konradrenner/kolabnotes-android#174] opened 2018-03-19 02:45 UTC
How to reproduce:

Type some text with "+"
Save document.
Open document again.
Result: "+" disappears, got replaced by whitespace.

Expected behaviour: "+" should stay.

Screenrecord video is below:
<img src="https://user-images.githubusercontent.com/17474312/37570198-1f1d0b2a-2aed-11e8-8a35-2d5f59d759c3.gif"/>

**Comment by konradrenner** [comment] 2018-03-20 05:25
Thanks for reporting. I will have a look at it

**Comment by konradrenner** [comment] 2018-05-21 17:04
It is not a bug of the kolab notes app, but of the richeditor component the app uses: https://github.com/wasabeef/richeditor-android/issues/155

there are already pull request, which fix the problem (e.g. https://github.com/wasabeef/richeditor-android/pull/123), but it seems wasabeef is not active any more.

so I created a really ugly workaround in the kolab notes app, which should fix the problem for this app.

**Comment by konradrenner** [comment] 2018-05-21 17:08
fixed with version 3.1.3

**Closed as completed by konradrenner** 2018-05-21 17:08 UTC
Labels: bug
