### ISSUE TITLE
Mark Shared Notebooks with Limited Permissions as Read-Only

### ISSUE THREAD

**Issue by grote** [konradrenner/kolabnotes-android#89] opened 2015-12-08 14:15 UTC
When sharing a notebook with these permissions:

```
Lookup  Read    Keep    Write   Insert
```

I get the following error while syncing.

```
org.kore.kolabnotes.android:sync E/onFolderSyncException: Folder name=Other Users/myuser/SharedFolder; korex.mail.MessagingException: A10 NO Permission denied;
                                                                                         nested exception is:
                                                                                        com.sun.mail.iap.CommandFailedException: A10 NO Permission denied
```

**Comment by grote** [comment] 2015-12-08 14:18
I even get this error with these permissions:

```
Lookup  Read    Keep    Write   Insert    Delete    Post
```

What permissions do you require on notebooks?

**Comment by konradrenner** [comment] 2015-12-09 13:08
@grote what changes did you make in the shared folder (create, update, delete of notes)? Do you see your own shared folder also as shared folder?

@danielegobbetti what permissions did you create on the test account which you provided me for the shared folders?

**Comment by grote** [comment] 2015-12-09 13:15
In this folder, notes were changed and one added. I didn't see this as a shared folder myself, because it is my folder.

I shared a notebook with you on Kolab Now with the above permissions for testing.

**Comment by konradrenner** [comment] 2015-12-09 13:43
Thanks for sharing, I hope to find the problem soon ;-)

**Comment by danielegobbetti** [comment] 2015-12-09 14:38
@konradrenner I created two folder shared with you, one with full access and the other one with:
search, read, keep state as seen(?), write flags, insert (copy to), annotate.

These are translations I am making from the GUI which is currently in italian for me, hence they may sound strange or inaccurate :)

P.S. Hi @grote ;-)

**Comment by konradrenner** [comment] 2015-12-09 16:37
the write flags could a problem because java mail doesn't know a method "deleteMail", it is just possible to set the DELETED flag. @grote can you verify this?

**Comment by grote** [comment] 2015-12-16 12:44
Maybe you don't want to allow people to delete existing notes. Should this not still work? We should make some tests with the webclient to see which permissions are essential there.

**Comment by konradrenner** [comment] 2015-12-16 16:11
The Problem is that IMAP doesn't know a altering notes function. Also I have not found a possibilty to delete message via Java Mail except with setting the "delete" flag.

@danielegobbetti and I have tested manipulation of notes which are in shared notebooks with limited permissions in the web ui. It is possible to change a note, but after saving the note is displayed 2 times, but 1 of those is not selectable. But I am not sure which permissions the notebook had.

**Comment by grote** [comment] 2015-12-16 22:37
hmm so in order to update a note, you always need to be able to also delete it?
@alecpl knows much more about IMAP than me. Maybe he can confirm what rights you need to have on a folder to be able to reasonably share notebooks with other people.

**Comment by alecpl** [comment] 2015-12-17 07:21
Yes. To update any kolab object you have to:
1. Create a copy of it
2. Delete the old one by
    2.1. Setting DELETED flag (STORE)
    2.2. Expunging the deleted message (UID EXPUNGE)

When listing kolab objects messages marked as deleted should be ignored.

So, if you want to share a folder and allow editing you need to allow deleting. If I remember correctly you need to add 'i' and 't' rights plus other ACLs that give read access. 'e' right would be needed too, but technicly nothing wrong will happen if the deleted message won't be expunged.

**Comment by konradrenner** [comment] 2015-12-17 18:54
@alecpl that's the way the kolabnotes-java/Java Mail combination handles it

@grote I think I cannot change something, except there is an IMAP command where I can check permissions and then e.g. lock the note, so that there is no error notification. If not, maybe things change when Kolab Servers support the fancy new JMAP protocol ;-)

**Comment by konradrenner** [comment] 2015-12-19 18:27
@grote @alecpl is there such an IMAP command?

**Comment by alecpl** [comment] 2015-12-19 18:55
MYRIGHTS, LISTRIGHTS, GETACL, etc. RFC4314

**Comment by konradrenner** [comment] 2015-12-19 21:42
@grote should the app block any modifications on a note which is in a folder with limited permissions, or is a sync error notification sufficient?

**Comment by konradrenner** [comment] 2015-12-19 21:44
@alecpl thanks for the fast answere!

**Comment by grote** [comment] 2015-12-19 22:03
I think the expected behavior would be to mark the notebook as read only and prevent the user from making any changes in read-only notebooks in the first place. For marking read-only, a little lock icon could be used.

**Comment by konradrenner** [comment] 2015-12-20 13:38
My analysis so far, according to https://tools.ietf.org/html/rfc4314#page-10 the expunge right is 'e', this is the constellation with which I tested:

Folder with no Expunge rights (editing of notes not possible):"Other Users/userXYZ/Notes/user_share" lrswin
Folder with all rights:"Other Users/userXYZ/Notes/user_share_complete_access" lrswipkxtecdn
Folder with Expunge rights:"Shared Folders/shared/test_notes" lrswitedn

so if one wants to create a new note in a shared folder with kolab notes, his user needs the rights to read the folder plus: isw (for details look at the rfc)

if one wants to modify/delete a note in a shared folder with kolab notes, his user needs the rigths to read the folder plus: et (for details look at the rfc, according to the rfc the x right is needed for deletion of folders, messages (or notes in our case) are expunged after they are marked with flag delete).

So I will check if notes are editable/deletable or it is just possible to create new notes or any modification is not permitted and signal it with different icons in the nav drawer

**Comment by konradrenner** [comment] 2015-12-20 14:25
Already implemented in the kolabnotes-java lib (New Version 2.1.0 published), now the app must be extended

**Comment by konradrenner** [comment] 2015-12-27 12:30
Done with 1.3.0, but I am not happy with the icons, which I use to mark notebooks in the drawer. Maybe someone can help me there, my knowledge with graphics and UI is more than limited ;-).

Notebooks are marked with following icons:
- no icon = > full permissions for notebook
- pencil => just deletion modification (for modification, there is also the creation permission necessary)
- create note => just note creation is possible
- lock => note can just be viewed

If one opens the detail of a note, he will get warned with a toast message. if he don't have some permissions. If he then tries to modify or delete a note, there will also be schown a toast message and the modification will not be done.

**Closed as completed by konradrenner** 2015-12-27 12:30 UTC
Labels: enhancement
