### ISSUE TITLE
no connection w/ lineageos 14.1

### ISSUE THREAD

**Issue by tjensch** [konradrenner/kolabnotes-android#172] opened 2018-02-28 20:47 UTC
Hello,
the kolab server is fairly recent (kolab 16) and with a qualys score of A+, the cell phone is lineageOS 14.1.
Whatever I tried, I am unable to connect kolabnotes. Everything else works (k9mail, caldavsync, carddavsync, seafile etc). I cant find any connection attempts in the server logfiles. I also tried any combination of the options (shared, kolab extensions) without much success. 
How should I proceed?

**Comment by konradrenner** [comment] 2018-03-05 10:07
Hi,
did you get any problem notification from the app via the android notification system? 
Please attach a screenshot or stacktrace of the problem.
Thanks Konrad

**Comment by tjensch** [comment] 2018-03-14 17:11
this error shows, when the account is configured for port 143:
![kn-error_143](https://user-images.githubusercontent.com/13883516/37418631-f56d8936-27b2-11e8-99ad-bafea9d01dff.png)
and this one with defaults (port 993):
![kn-error_993](https://user-images.githubusercontent.com/13883516/37418632-f58f7078-27b2-11e8-9596-177bb3ae64e0.png)

**Comment by konradrenner** [comment] 2018-03-15 08:45
Can you please also send me the settings (with the extended options area opened) of this account?

**Comment by tjensch** [comment] 2018-03-16 08:06
I left the other Options at the defaults, i.e. 
+ other Kolab Server
[IMAP root folder] Notes
[port] 143
[sync interval] 24
[x] SSL enabled
[x] Kolab extensions
[x] Shared notebooks

Although it doesnt make a difference whether I uncheck "Kolab extensions" and / or "Shared notebook" (as suggested in other Issues). 
It also doesnt connect if I switch to "IMAP Server".
(Ultimately I like to use the "Shared notebook" feature, since I have a couple of shared ones.)

**Comment by konradrenner** [comment] 2018-03-16 08:21
Did you specify the hostname of the kolab server the exact same way as in the k9 app? Is there a "Notes" folder on your Kolab installation, which is also marked to contain notes (can be specified in the folder settings)?

**Comment by tjensch** [comment] 2018-03-16 09:05
in k9 it is like: kolab.example.org, which is how I put it in kolabnotes. In k9 I can addititionally specify "STARTTLS". 
I checked on the server and my user has a /var/spool/imap/domain/.../Notes directory with notes in it. It is also marked as special Folder "Notes" when checking it via roundcube.

As I wrote in the beginning, my SSL-setup is somewhat tight, in order to archieve a Qualys A+ rating. Is it possible, the kolabnotes ssl-library (?) is not capable of that?
![kn-ssl_1](https://user-images.githubusercontent.com/13883516/37512131-81574dac-2901-11e8-9539-e66ccb437239.png)
![kn-ssl_2](https://user-images.githubusercontent.com/13883516/37512132-816efc9a-2901-11e8-944d-660015fdd08b.png)
![kn-ssl_3](https://user-images.githubusercontent.com/13883516/37512133-8188213e-2901-11e8-9f93-47e48af86a6f.png)

**Comment by konradrenner** [comment] 2018-03-16 12:19
It could be a problem that just TLS 1.2 is accepted by your server.
I found this article: https://discretemkt.wordpress.com/2014/11/15/javamail-enables-or-disables-sslv3/

I will add the following, maybe it solves the problem (it looks like Java Mail does not active TLS 1.2 per default):

Properties props = new Properties();
        props.setProperty("mail.host", "smtp.example.com");
        props.setProperty("mail.smtps.ssl.protocols", "TLSv1 TLSv1.1 TLSv1.2");
        
        Session session = Session.getInstance(props);

**Comment by konradrenner** [comment] 2018-03-16 22:15
added the mentioned property, I hope this fixes the problem, because I cannot reproduce it.
Already available in the Google Play Beta Channel.

@tjensch my try to fix it, is released with version 3.1.2 of the app. Please test it and give me feedback if it works for you now

**Comment by tjensch** [comment] 2018-03-17 10:29
thank you very much! your fix works! I now can access my notes with your fine programme :)

**Comment by konradrenner** [comment] 2018-03-17 20:31
Perfect, good news :-)

**Closed as completed by konradrenner** 2018-03-17 20:31 UTC
Labels: Analysis
