### ISSUE TITLE
Kolab 16 - synching of shared notes not working

### ISSUE THREAD

**Issue by gino909** [konradrenner/kolabnotes-android#157] opened 2017-03-09 18:51 UTC
Hi
With Kolab 16 the sync of shared notes seems not working.
With the parameter "sync shared notes" deactivated the sync of notes for my user works. If I want to sync shared notes I have to activate the paramter in the account settings. But then the sync does not work anymore. Also my own notes will not be synced anymore.
Can you tell me if I have to change some settings?
For your knowledge. the notes from the other user are shared with full rights and I have activated the shared folder in the folder management of Roundcube.
My android device runs on android 5.0.1
Thank you for your assistance
BR, Gino

**Comment by konradrenner** [comment] 2017-03-10 10:20
Hi,
thanks for reporting. I am not able to reproduce it, because I don't have a server with shared notebooks. Maybe you can provide me an account on your server, so that I can test it and hopefully fix it ;-)

**Comment by gino909** [comment] 2017-03-10 12:42
Hi Konrad
Well, I think it would be better if you setup a kolab 16 installation at your location to test and develop the missing parts. I think there are some addtional things to test.... I tried to create a note on the android device with image and attachment... after sync the notes was no more possible to open in roundcube... time out... to fix it I had to empty the folder.
BR, Gino

**Comment by konradrenner** [comment] 2017-03-11 19:40
Yeah I had one, but it is hard to get a server working and I re installed my OS :-/ . The problem with the attachments is not the app, they are not supported by the Kolab Web UI (but are int the format). So they will be synced between Android devices, but it can be, that you are not able to open such notes on the Web UI. But timeouts I was never facing, I will also have a look on that as soon as I have a running Kolab server again.

**Comment by konradrenner** [comment] 2017-03-15 17:29
should be fixed in the next version of the app

**Closed as completed by konradrenner** 2017-03-15 17:29 UTC
